/* LIVELLO 1 - RICOVERI INTERVENTI */


OPTIONS MPRINT;
OPTIONS COMPRESS =YES;
proc printto log="C:\Users\r.blaco\Desktop\scripts Modello predittivo 20220706\logs\L1_SDO_INTERV.txt" new;
run;

/* libname dei dati iniziali di input, dati forniti dal ministero*/
libname  INPUT "T:\202204_modello\Input Stratificazione";
%let INPUT = INPUT;

/* La libname temporanea si chiamer� "temp", al momento impostata sulla work*/
libname  TEMP "T:\202204_modello\Output camp\temp";
%let TEMP = TEMP;

/* La Libname che conterr� le tabelle create la chiamo LIBRARY */
LIBNAME OUTPUT "T:\202204_modello\Output camp\output";
%let OUTPUT = OUTPUT;

/* La Libname che contiene la tabella anagrafica del campione di 4mln*/
libname camp "T:\202204_modello\Output camp";

%global check_indicatore;


%let dt_riferimento = "31122019";




%macro L1_SDO_INTERV(ID_CLASSIFICAZIONE=,reg=);

	PROC SQL;
		SELECT count(*) INTO :check_indicatore FROM input.CRIT_L1_SDO_PROCED WHERE ID_CLASSIFICAZIONE = &ID_CLASSIFICAZIONE.
	;QUIT;

	%IF %eval(&check_indicatore. > 0) %THEN %DO;
	*********PROFONDITA TEMPORALE********************;
		PROC SQL;
			CREATE TABLE temp.CRIT_L1_INTERV_PROFONDITA  AS
				SELECT
					CRIT_L1.ID_CLASSIFICAZIONE,
					CRIT_L1.ID_INDICATORE,
					CRIT_L1.FL_INTERV_PRIM,
					CRIT_L1.ID_INTERVENTO,
					CRIT_L1.FL_INI,
					LENGTH(ID_INTERVENTO) AS LEN_INTERV,
					intnx("month",input(&DT_RIFERIMENTO.,ddmmyy10.), PT.NM_PROFONDITA_A_ANNI*-12, 's')+1  AS DIMISS_INI format ddmmyy10.,
					intnx("month",input(&DT_RIFERIMENTO.,ddmmyy10.), PT.NM_PROFONDITA_DA_ANNI*-12, 's') AS DIMISS_FINE format ddmmyy10.
				FROM
					input.CRIT_L1_SDO_PROCED CRIT_L1
					JOIN input.PROFONDITA_TEMPORALE PT ON
						CRIT_L1.ID_CLASSIFICAZIONE=PT.ID_CLASSIFICAZIONE AND CRIT_L1.ID_INDICATORE=PT.ID_INDICATORE
				WHERE
					CRIT_L1.ID_CLASSIFICAZIONE=&ID_CLASSIFICAZIONE.
		;QUIT;

	**********FILTRO RICOVERI CON INTERVENTI IN LISTA********************;

		/*PROC SQL;
				CREATE TABLE temp.TMP_L1_INTERV_01_&reg AS
					SELECT
						ID_ANONIMO,
						ID_INTERV_PRINC,
						ID_INTERV_SEC_1,
						ID_INTERV_SEC_2,
						ID_INTERV_SEC_3,
						ID_INTERV_SEC_4,
						ID_INTERV_SEC_5,
						DT_DIMISSIONE
					from output.sdo_&reg RIC,
					(SELECT DISTINCT ID_INTERV_PRINC, LEN_INTERV, FL_INI FROM temp.CRIT_L1_INTERV_PROFONDITA WHERE ID_CLASSIFICAZIONE = &ID_CLASSIFICAZIONE.) T
					WHERE
						(T.FL_INI='0' AND(
							compress(RIC.ID_INTERV_PRINC,".")=T.ID_INTERV_PRINC OR
							compress(RIC.ID_INTERV_SEC_1,".")=T.ID_INTERV_PRINC OR
							compress(RIC.ID_INTERV_SEC_2,".")=T.ID_INTERV_PRINC OR
							compress(RIC.ID_INTERV_SEC_3,".")=T.ID_INTERV_PRINC OR
							compress(RIC.ID_INTERV_SEC_4,".")=T.ID_INTERV_PRINC OR
							compress(RIC.ID_INTERV_SEC_5,".")=T.ID_INTERV_PRINC))
						OR (T.FL_INI='1' AND(
							substr(compress(RIC.ID_INTERV_PRINC,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC OR
							substr(compress(RIC.ID_INTERV_SEC_1,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC OR
							substr(compress(RIC.ID_INTERV_SEC_2,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC OR
							substr(compress(RIC.ID_INTERV_SEC_3,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC OR
							substr(compress(RIC.ID_INTERV_SEC_4,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC OR
							substr(compress(RIC.ID_INTERV_SEC_5,"."),1,T.LEN_INTERV)=T.ID_INTERV_PRINC))
			;QUIT;
		*/

	**********RICOVERI********************;
		PROC SQL;
			CREATE TABLE temp.TMP_L1_INTERV_02_&reg AS
				SELECT
					T.ID_CLASSIFICAZIONE,
					T.ID_INDICATORE,
					RIC_F.ID_ANONIMO,
					RIC_F.DT_DIMISSIONE
				FROM
					output.sdo_&reg RIC_F,
					(SELECT * FROM temp.CRIT_L1_INTERV_PROFONDITA WHERE FL_INTERV_PRIM='1' AND ID_CLASSIFICAZIONE=&ID_CLASSIFICAZIONE.) T
				WHERE
					(T.FL_INI='0' AND compress(RIC_F.ID_INTERV_PRINC, ".")=T.ID_INTERVENTO) OR
					(T.FL_INI='1' AND substr(compress(RIC_F.ID_INTERV_PRINC,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO)
					AND RIC_F.DT_DIMISSIONE BETWEEN T.DIMISS_INI AND T.DIMISS_FINE
			UNION ALL
				SELECT
					T.ID_CLASSIFICAZIONE,
					T.ID_INDICATORE,
					RIC_F.ID_ANONIMO,
					RIC_F.DT_DIMISSIONE
				FROM
					output.sdo_&reg RIC_F,
					(SELECT * FROM temp.CRIT_L1_INTERV_PROFONDITA WHERE FL_INTERV_PRIM='0' AND ID_CLASSIFICAZIONE=&ID_CLASSIFICAZIONE.) T
				WHERE
						(T.FL_INI='0' AND(
							compress(RIC_F.ID_INTERV_PRINC,".")=T.ID_INTERVENTO OR
							compress(RIC_F.ID_INTERV_SEC_1,".")=T.ID_INTERVENTO OR
							compress(RIC_F.ID_INTERV_SEC_2,".")=T.ID_INTERVENTO OR
							compress(RIC_F.ID_INTERV_SEC_3,".")=T.ID_INTERVENTO OR
							compress(RIC_F.ID_INTERV_SEC_4,".")=T.ID_INTERVENTO OR
							compress(RIC_F.ID_INTERV_SEC_5,".")=T.ID_INTERVENTO))
						OR (T.FL_INI='1' AND(
							substr(compress(RIC_F.ID_INTERV_PRINC,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO OR
							substr(compress(RIC_F.ID_INTERV_SEC_1,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO OR
							substr(compress(RIC_F.ID_INTERV_SEC_2,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO OR
							substr(compress(RIC_F.ID_INTERV_SEC_3,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO OR
							substr(compress(RIC_F.ID_INTERV_SEC_4,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO OR
							substr(compress(RIC_F.ID_INTERV_SEC_5,"."),1,T.LEN_INTERV)=T.ID_INTERVENTO))
					AND RIC_F.DT_DIMISSIONE BETWEEN T.DIMISS_INI AND T.DIMISS_FINE
		;QUIT;

		PROC SQL;
			CREATE TABLE temp.L1_SDO_INTERV_WRK_&reg AS
				SELECT
					ID_CLASSIFICAZIONE,
					ID_INDICATORE,
					ID_ANONIMO,
					count(*) AS QTA,
					MIN(DT_DIMISSIONE) as MIN_DIMISS FORMAT DDMMYY10.,
					MAX(DT_DIMISSIONE) as MAX_DIMISS FORMAT DDMMYY10.
				FROM
					temp.TMP_L1_INTERV_02_&reg
			GROUP BY
					ID_CLASSIFICAZIONE,
					ID_ANONIMO,
					ID_INDICATORE
		;QUIT;


		PROC SQL;
			DROP TABLE temp.TMP_L1_INTERV_01_&reg,
			temp.TMP_L1_INTERV_02_&reg,
			temp.CRIT_L1_INTERV_PROFONDITA
		;QUIT;

	%END;

		proc delete data= temp.CRIT_L1_INTERV_PROFONDITA temp.TMP_L1_INTERV_02_&reg ;
		run;
%MEND;


/* prova macro
*/
/*
%let dt_riferimento = "31122018";
%L1_SDO_INTERV(ID_CLASSIFICAZIONE = 9);
*/

%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=010);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=020);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=030);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=041);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=042);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=050);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=060);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=070);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=080);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=090);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=100);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=110);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=120);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=130);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=140);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=150);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=160);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=170);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=180);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=190);
%L1_SDO_INTERV(ID_CLASSIFICAZIONE=9,reg=200);
