/* LIVELLO 1 - RICOVERI DIAGNOSI */
proc printto log="C:\Users\r.blaco\Desktop\scripts Modello predittivo 20220706\logs\L3_FINALE.txt" new;
run;
OPTIONS MPRINT;
OPTIONS COMPRESS =YES;


/* libname dei dati iniziali di input, dati forniti dal ministero*/
libname  INPUT "T:\202204_modello\Input Stratificazione";
%let INPUT = INPUT;

/* La libname temporanea si chiamer� "temp", al momento impostata sulla work*/
libname  TEMP "T:\202204_modello\Output camp\temp";
%let TEMP = TEMP;

/* La Libname che conterr� le tabelle create la chiamo LIBRARY */
LIBNAME OUTPUT "T:\202204_modello\Output camp\output";
%let OUTPUT = OUTPUT;

libname camp "T:\202204_modello\Output camp";

%global check_indicatore;

%let dt_riferimento = "31122019";


%macro L3(ID_CLASSIFICAZIONE=, reg=); /* LIVELLO 3 */

	/*** INSERT INDICATORI SENZA CRITERI DI INCLUSIONE / ESCLUSIONE DI LIVELLO 3 *******************/

	PROC SQL;
			CREATE TABLE &TEMP..FINALE_L3_&reg AS
				SELECT
					ID_CLASSIFICAZIONE,
					ID_INDICATORE,
					ID_ANONIMO
				FROM
					&TEMP..L2_WRK_&reg
				WHERE
					ID_INDICATORE not contains "_AND" /*-------> Da aggiornare con le nomenclature _AND e _ESC ed eventualmente altre presenti*/
					AND  CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) NOT IN (SELECT CATS(D.ID_CLASSIFICAZIONE, D.ID_INDICATORE) FROM input.CRIT_L3 D)
	;QUIT;

	/*** INSERT INDICATORI CON CRITERI DI INCLUSIONE DI LIVELLO 3 *******************/
	PROC SQL;
			INSERT INTO &TEMP..FINALE_L3_&reg (
					ID_CLASSIFICAZIONE
					, ID_INDICATORE
					, ID_ANONIMO
				)
				SELECT
						ID_CLASSIFICAZIONE,
						ID_INDICATORE,
						ID_ANONIMO
					FROM
						&TEMP..L2_WRK_&reg
					WHERE
						CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) IN (
							SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='1'
							EXCEPT
							SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='2'
						)
				INTERSECT
				SELECT
						A.ID_CLASSIFICAZIONE,
						B.ID_INDICATORE,
						A.ID_ANONIMO
					FROM
						&TEMP..L2_WRK_&reg A,
						input.CRIT_L3 B
					WHERE
						A.ID_CLASSIFICAZIONE=B.ID_CLASSIFICAZIONE
						AND A.ID_INDICATORE=B.ID_INDICATORE_RIF
						AND B.ID_TIPOLOGIA='1'
		;QUIT;

	/*** INSERT INDICATORI CON CRITERI DI ESCLUSIONE DI LIVELLO 3 *******************/
	PROC SQL;
			INSERT INTO &TEMP..FINALE_L3_&reg (
					ID_CLASSIFICAZIONE
					, ID_INDICATORE
					, ID_ANONIMO
				)
				SELECT
						ID_CLASSIFICAZIONE,
						ID_INDICATORE,
						ID_ANONIMO
					FROM
						&TEMP..L2_WRK_&reg
					WHERE
						CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) IN (
							SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='2'
							EXCEPT
							SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='1'
						)
				EXCEPT
				SELECT
						A.ID_CLASSIFICAZIONE,
						B.ID_INDICATORE,
						A.ID_ANONIMO
					FROM
						&TEMP..L2_WRK_&reg A,
						input.CRIT_L3 B
					WHERE
						A.ID_CLASSIFICAZIONE=B.ID_CLASSIFICAZIONE
						AND A.ID_INDICATORE=B.ID_INDICATORE_RIF
						AND B.ID_TIPOLOGIA='2'
		;QUIT;

	/*** INSERT INDICATORI CON CRITERI DI INCLUSIONE ED ESCLUSIONE DI LIVELLO 3 *******************/
	PROC SQL;
			INSERT INTO &TEMP..FINALE_L3_&reg (
					ID_CLASSIFICAZIONE
					, ID_INDICATORE
					, ID_ANONIMO
				)
				SELECT *
				FROM (
					SELECT
							ID_CLASSIFICAZIONE,
							ID_INDICATORE,
							ID_ANONIMO
						FROM
							&TEMP..L2_WRK_&reg
						WHERE
							CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) IN (
								SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='1'
								INTERSECT
								SELECT CATS(ID_CLASSIFICAZIONE, ID_INDICATORE) FROM input.CRIT_L3 WHERE ID_TIPOLOGIA='2'
							)
					INTERSECT
					SELECT
							A.ID_CLASSIFICAZIONE,
							B.ID_INDICATORE,
							A.ID_ANONIMO
						FROM
							&TEMP..L2_WRK_&reg A,
							input.CRIT_L3 B
						WHERE
							A.ID_CLASSIFICAZIONE=B.ID_CLASSIFICAZIONE
							AND A.ID_INDICATORE=B.ID_INDICATORE_RIF
							AND B.ID_TIPOLOGIA='1'
				) AA
				EXCEPT
				SELECT
						A.ID_CLASSIFICAZIONE,
						B.ID_INDICATORE,
						A.ID_ANONIMO
					FROM
						&TEMP..L2_WRK_&reg A,
						input.CRIT_L3 B
					WHERE
						A.ID_CLASSIFICAZIONE=B.ID_CLASSIFICAZIONE
						AND A.ID_INDICATORE=B.ID_INDICATORE_RIF
						AND B.ID_TIPOLOGIA='2'
		;QUIT;

%MEND;

/* prova macro
*/
/*
%let dt_riferimento = "31122018";
%L3(ID_CLASSIFICAZIONE = 9);
*/


%L3(ID_CLASSIFICAZIONE=9,reg=010);
%L3(ID_CLASSIFICAZIONE=9,reg=020);
%L3(ID_CLASSIFICAZIONE=9,reg=030);
%L3(ID_CLASSIFICAZIONE=9,reg=041);
%L3(ID_CLASSIFICAZIONE=9,reg=042);
%L3(ID_CLASSIFICAZIONE=9,reg=050);
%L3(ID_CLASSIFICAZIONE=9,reg=060);
%L3(ID_CLASSIFICAZIONE=9,reg=070);
%L3(ID_CLASSIFICAZIONE=9,reg=080);
%L3(ID_CLASSIFICAZIONE=9,reg=090);
%L3(ID_CLASSIFICAZIONE=9,reg=100);
%L3(ID_CLASSIFICAZIONE=9,reg=110);
%L3(ID_CLASSIFICAZIONE=9,reg=120);
%L3(ID_CLASSIFICAZIONE=9,reg=130);
%L3(ID_CLASSIFICAZIONE=9,reg=140);
%L3(ID_CLASSIFICAZIONE=9,reg=150);
%L3(ID_CLASSIFICAZIONE=9,reg=160);
%L3(ID_CLASSIFICAZIONE=9,reg=170);
%L3(ID_CLASSIFICAZIONE=9,reg=180);
%L3(ID_CLASSIFICAZIONE=9,reg=190);
%L3(ID_CLASSIFICAZIONE=9,reg=200);
