libname  TEMP "T:\202204_modello\Output camp\temp";


DATA TEMP.ID_PAT_CRONICI_TUTTE_REGIONE;
SET TEMP.ID_PAT_CRONICI_010 TEMP.ID_PAT_CRONICI_020 TEMP.ID_PAT_CRONICI_030 TEMP.ID_PAT_CRONICI_041 TEMP.ID_PAT_CRONICI_042
TEMP.ID_PAT_CRONICI_050 TEMP.ID_PAT_CRONICI_060 TEMP.ID_PAT_CRONICI_070 TEMP.ID_PAT_CRONICI_080
TEMP.ID_PAT_CRONICI_090 TEMP.ID_PAT_CRONICI_100 TEMP.ID_PAT_CRONICI_110 TEMP.ID_PAT_CRONICI_120
TEMP.ID_PAT_CRONICI_130 TEMP.ID_PAT_CRONICI_140 TEMP.ID_PAT_CRONICI_150 TEMP.ID_PAT_CRONICI_160
TEMP.ID_PAT_CRONICI_170 TEMP.ID_PAT_CRONICI_180 TEMP.ID_PAT_CRONICI_190 TEMP.ID_PAT_CRONICI_200;
RUN; 


PROC SORT DATA=TEMP.ID_PAT_CRONICI_TUTTE_REGIONE OUT=CRONICI;BY ID_ANONIMO ID_PATOLOGIA;WHERE ID_PATOLOGIA NE "";RUN;

DATA monopatologici;
SET CRONICI;
BY ID_ANONIMO;
N_PAT+1;
IF FIRST.ID_ANONIMO THEN N_PAT=1;
RUN;

DATA monopatologici2;*2.077.491;
SET monopatologici;
WHERE N_PAT=1;
RUN;


/*TABELLA COSTI*/

DATA TEMP.COSTO_TOT_TUTTE_REGIONE;
SET TEMP.COSTO_TOT_010 TEMP.COSTO_TOT_020 TEMP.COSTO_TOT_030 TEMP.COSTO_TOT_041 TEMP.COSTO_TOT_042 TEMP.COSTO_TOT_050 TEMP.COSTO_TOT_060
TEMP.COSTO_TOT_070 TEMP.COSTO_TOT_080 TEMP.COSTO_TOT_090 TEMP.COSTO_TOT_100 TEMP.COSTO_TOT_110 TEMP.COSTO_TOT_120
TEMP.COSTO_TOT_130 TEMP.COSTO_TOT_140 TEMP.COSTO_TOT_150 TEMP.COSTO_TOT_160 TEMP.COSTO_TOT_170 TEMP.COSTO_TOT_180
TEMP.COSTO_TOT_190 TEMP.COSTO_TOT_200
;RUN;

PROC SQL;
CREATE TABLE COSTO AS SELECT *
FROM TEMP.COSTO_TOT_TUTTE_REGIONE
WHERE ID_ANONIMO IN(SELECT ID_ANONIMO FROM monopatologici2)
;QUIT;


PROC SQL;*2040935;
CREATE TABLE RANKING AS SELECT A.*, B.VAL_TOT
FROM MONOPATOLOGICI2 AS A LEFT JOIN COSTO AS B
ON A.ID_ANONIMO=B.ID_ANONIMO
;QUIT;

PROC SORT DATA=RANKING OUT=RANKING2 NODUPKEY;BY ID_ANONIMO;RUN;*2040935 QUINDI NON CI SONO DUPPLICATI;

PROC SORT DATA=RANKING2;BY ID_PATOLOGIA VAL_TOT;RUN;

PROC SQL;
CREATE TABLE RANKING3 AS SELECT ID_PATOLOGIA,MEAN(COALESCE(VAL_TOT,0)) AS MEAN_VAL_TOT
FROM RANKING2
GROUP BY ID_PATOLOGIA
;QUIT;

PROC SORT DATA=RANKING3;BY DESCENDING MEAN_VAL_TOT ;RUN;

*RANKING MODO DISCENDENTE;

DATA RANKING3;
SET RANKING3;
RANKING=_N_;
RUN;

libname  INPUT "T:\202204_modello\Input Stratificazione";

PROC SQL;
CREATE TABLE AREA_PATOLOGICA AS SELECT A.ID_CLASSIFICAZIONE, A.ID_PATOLOGIA,A.DESC_PATOLOGIA,A.ID_AREA_PATOLOGICA,A.DESC_AREA_PATOLOGICA,
B.RANKING
FROM INPUT.AREA_PATOLOGICA AS A LEFT JOIN RANKING3 AS B
ON A.ID_PATOLOGIA=B.ID_PATOLOGIA
;QUIT;

*PN05 NON CI SONO NEI MONOPATOLOGICI, HO VISTO CHE ASMA � NELLA ULTIMA COME RANKING QUINDI CONCORDA LASCIARLA COME ULTIMA QUESTA QUA
VISTO CHE APPARTIENE ALLA FAMIGLIA DEL ASMA;
DATA AREA_PATOLOGICA2;
SET AREA_PATOLOGICA;
IF ID_PATOLOGIA="ED15" THEN RANKING=79;
IF ID_PATOLOGIA="PN05" THEN RANKING=80;
RUN;


PROC SORT DATA=AREA_PATOLOGICA2;BY  RANKING ;RUN;

DATA INPUT.AREA_PATOLOGICA2;
SET AREA_PATOLOGICA2;
RUN;
 

proc export data = INPUT.AREA_PATOLOGICA2
	outfile = "T:\202204_modello\Output camp\tabelle_analisi_codice\ANALISI\RANKING_MONO_PRE_COMBINAZIONI.xlsx"
	dbms = xlsx
	replace;
run;
