libname input "T:\202204_modello\Output camp\temp";
/*Inserire la cartella dove si vuole avere i risultati finali, creare cartella "output"
eseguendo il percorso: T:\202204_modello\Output camp\temp\ - creare cartella- */

/*inserire percorso*/
%let percorso=T:\202204_modello\Output camp\temp\output;

libname output "&&percorso.";

proc sql;
		create table info_mono_str as
		select STR_GROUP,
			sum(FREQ) as FREQ_MONO,SESSO, CLASSE_ETA, /*ID_ETA,*/ REGIONE, REG_DESC,
			sum(SUM_VAL) as COSTO_TOTALE_MONO,
			sum(SUM_VAL)/ sum(FREQ) as COSTO_MEDIO_MONO,
			sum(SUM_SQUARE_VAL)/sum(FREQ)-(sum(SUM_VAL)/sum(FREQ))**2 as VARIANCE_MONO,
			sqrt(sum(SUM_SQUARE_VAL)/sum(FREQ)-(sum(SUM_VAL)/sum(FREQ))**2) as SD_MONO,
			sum(SUM_VAL_AMB) as COSTO_TOTALE_AMB_MONO,
			sum(SUM_RICOVERI) as COSTO_TOTALE_RICOVERI_MONO,
			sum(SUM_COSTO_FARMA) as COSTO_TOTALE_FARMA_MONO,
			sum(SUM_FARMA_TERR) as COSTO_TOTALE_FARMA_TERR_MONO,
			sum(SUM_HOSPICE) as COSTO_TOTALE_HOSPICE_MONO,
			sum(SUM_PS) as COSTO_TOTALE_PS_MONO


		from output.comb_str
		where /*N_PAT_INI=1*/N_PAT=1
		group by STR_GROUP, SESSO, CLASSE_ETA, /*ID_ETA,*/ REGIONE, REG_DESC
;quit;				


proc sql;
		create table tabella_finale as
		select a.*,b.FREQ_MONO,
			            b.COSTO_TOTALE_MONO,
			             b.COSTO_MEDIO_MONO,
			                b.VARIANCE_MONO,
			                      b.SD_MONO,
			        b.COSTO_TOTALE_AMB_MONO,
			   b.COSTO_TOTALE_RICOVERI_MONO,
			      b.COSTO_TOTALE_FARMA_MONO,
			 b.COSTO_TOTALE_FARMA_TERR_MONO,
			    b.COSTO_TOTALE_HOSPICE_MONO,
			          b.COSTO_TOTALE_PS_MONO


		from OUTPUT.STRATIFICATION as a left join info_mono_str as b
		on a.STR_GROUP=b.STR_GROUP and  a.SESSO=b.SESSO and a.CLASSE_ETA=b.CLASSE_ETA and a.REGIONE=b.REGIONE
;quit;				

data tabella;
set tabella_finale;
SUM_VAL_CORRETTA         =SUM_VAL*11.66072975;
SUM_VAL_AMB_CORRETTA     =SUM_VAL_AMB*11.66072975;
SUM_VAL_FAR_CORRETTA     =SUM_VAL_FARMA_TERR*11.66072975;
SUM_VAL_FARMA_CORRETTA   =SUM_VAL_FARMA*11.66072975;
SUM_VAL_HOSPICE_CORRETTA =SUM_VAL_HOSPICE*11.66072975;
SUM_VAL_PS_CORRETTA      =SUM_VAL_PS*11.66072975;
SUM_VAL_RICOVERI_CORRETTA=SUM_VAL_RICOVERI*11.66072975;
FREQ_CORRETTA=FREQ*11.66072975;
COSTO_TOTALE_AMB_MONO     =COSTO_TOTALE_AMB_MONO*11.66072975;     
COSTO_TOTALE_FAR_MONO     =COSTO_TOTALE_FARMA_TERR_MONO*11.66072975;     
COSTO_TOTALE_FARMA_MONO   =COSTO_TOTALE_FARMA_MONO*11.66072975;   
COSTO_TOTALE_HOSPICE_MONO =COSTO_TOTALE_HOSPICE_MONO*11.66072975; 
COSTO_TOTALE_MONO         =COSTO_TOTALE_MONO*11.66072975;         
COSTO_TOTALE_PS_MONO      =COSTO_TOTALE_PS_MONO*11.66072975;      
COSTO_TOTALE_RICOVERI_MONO=COSTO_TOTALE_RICOVERI_MONO*11.66072975;
FREQ_MONO=FREQ_MONO*11.66072975;
rename COSTO_MEDIO_FARMA_TERR=COSTO_MEDIO_FAR;
run;


proc means data=tabella sum;var SUM_VAL_CORRETTA SUM_VAL;run;

proc sql;
create table tabella_stratificazione
as select 
STR_GROUP,sesso,CLASSE_ETA,REGIONE,reg_desc,FREQ_CORRETTA,COSTO_MEDIO,COSTO_MEDIO_AMB,COSTO_MEDIO_RICOVERI,COSTO_MEDIO_FARMA,COSTO_MEDIO_FAR,
COSTO_MEDIO_HOSPICE,COSTO_MEDIO_PS,SUM_VAL_AMB_CORRETTA,SUM_VAL_FAR_CORRETTA,SUM_VAL_FARMA_CORRETTA,SUM_VAL_HOSPICE_CORRETTA,SUM_VAL_PS_CORRETTA,
SUM_VAL_RICOVERI_CORRETTA,SUM_VAL_CORRETTA,FREQ_MONO,COSTO_MEDIO_MONO,COSTO_TOTALE_AMB_MONO,COSTO_TOTALE_FAR_MONO,COSTO_TOTALE_FARMA_MONO,
COSTO_TOTALE_HOSPICE_MONO,COSTO_TOTALE_PS_MONO,COSTO_TOTALE_RICOVERI_MONO,COSTO_TOTALE_MONO
from  tabella
;quit;
