%macro group_for_stratification(data=);

	proc sql;
	create table output.stratification as 
	select 
		STR_GROUP,
		SESSO,
		CLASSE_ETA,
		/*ID_ETA,*/
		REGIONE,
		REG_DESC,
		sum(FREQ) as FREQ,
		/*sum(NUM_DECESSI) as NUM_DECESSI,
		sum(NUM_RICOVERI) as NUM_RICOVERI,*/

/*COSTO MEDIO*/
		sum(SUM_VAL)/sum(FREQ) as COSTO_MEDIO,
		sum(SUM_VAL_AMB)/sum(FREQ) as COSTO_MEDIO_AMB,
		sum(SUM_RICOVERI)/sum(FREQ) as COSTO_MEDIO_RICOVERI,
		sum(SUM_COSTO_FARMA)/sum(FREQ) as COSTO_MEDIO_FARMA,
		sum(SUM_FARMA_TERR)/sum(FREQ) as COSTO_MEDIO_FARMA_TERR,
		sum(SUM_HOSPICE)/sum(FREQ) as COSTO_MEDIO_HOSPICE,
		sum(SUM_PS)/sum(FREQ) as COSTO_MEDIO_PS,
/*SOMMA*/
		sum(SUM_VAL) as SUM_VAL,	
		sum(SUM_VAL_AMB)as SUM_VAL_AMB,
		sum(SUM_RICOVERI)as SUM_VAL_RICOVERI,
		sum(SUM_COSTO_FARMA)as SUM_VAL_FARMA,
		sum(SUM_FARMA_TERR)as SUM_VAL_FARMA_TERR,
		sum(SUM_HOSPICE) as SUM_VAL_HOSPICE,
		sum(SUM_PS) as SUM_VAL_PS,
/*LOG*/
		sum(SUM_LOG_VAL) as SUM_LOG_VAL,
		sum(SUM_LOG_VAL_AMB) as SUM_LOG_VAL_AMB,
		sum(SUM_LOG_RICOVERI) as SUM_LOG_VAL_RICOVERI,
		sum(SUM_LOG_COSTO_FARMA) as SUM_LOG_VAL_FARMA,
		sum(SUM_LOG_FARMA_TERR) as SUM_LOG_VAL_FARMA_TERR,
		sum(SUM_LOG_HOSPICE) as SUM_LOG_VAL_HOSPICE,
		sum(SUM_LOG_PS) as SUM_LOG_VAL_PS,

/*SQUARE*/
		sum(SUM_SQUARE_VAL) as SUM_SQUARE_VAL,
		sum(SUM_SQUARE_VAL_AMB) as SUM_SQUARE_VAL_AMB,
		sum(SUM_SQUARE_RICOVERI) as SUM_SQUARE_VAL_RICOVERI,
		sum(SUM_SQUARE_COSTO_FARMA) as SUM_SQUARE_VAL_FARMA,
		sum(SUM_SQUARE_FARMA_TERR) as SUM_SQUARE_VAL_FARMA_TERR,
		sum(SUM_SQUARE_HOSPICE) as SUM_SQUARE_VAL_HOSPICE,
		sum(SUM_SQUARE_PS) as SUM_SQUARE_VAL_PS,
/*SQUARE-LOG*/
		sum(SUM_SQUARE_LOG_VAL) as SUM_SQUARE_LOG_VAL,
		sum(SUM_SQUARE_LOG_VAL_AMB) as SUM_SQUARE_LOG_VAL_AMB,
		sum(SUM_SQUARE_LOG_RICOVERI) as SUM_SQUARE_LOG_VAL_RICOVERI,
		sum(SUM_SQUARE_LOG_COSTO_FARMA) as SUM_SQUARE_LOG_VAL_FARMA,
		sum(SUM_SQUARE_LOG_FARMA_TERR) as SUM_SQUARE_LOG_VAL_FARMA_TERR,
		sum(SUM_SQUARE_LOG_HOSPICE) as SUM_SQUARE_LOG_VAL_HOSPICE,
		sum(SUM_SQUARE_LOG_PS) as SUM_SQUARE_LOG_VAL_PS
	from &data
	group by STR_GROUP, SESSO, CLASSE_ETA, /*ID_ETA,*/ REGIONE, REG_DESC;
	quit;

%mend;


*%group_for_stratification(data=output.COMB_STR);
